name: Decrypt GPG Key Workflow

on:
  workflow_call:
    secrets:
      GPG_USER_MAP_PASSPHRASE:
        required: true

jobs:
  decrypt-gpg-key:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Decrypt GPG Key
        run: |
          chmod +x ./decrypt.sh
          GPG_PASSPHRASE=${{ inputs.GPG_USER_MAP_PASSPHRASE }} ./decrypt.sh
