name: Slack Notification Workflow

on:
  workflow_call:
    inputs:
      GITHUB_USER:
        required: true
        type: string
      REPOSITORY:
        required: true
        type: string
      PR_TITLE:
        required: true
        type: string
      ACTION:
        required: true
        type: string
      PR_URL:
        required: true
        type: string
    secrets:
      SLACK_BOT_TOKEN:
        required: true
      GENERAL_CHANNEL_ID:  # Use the general channel ID secret here
        required: true
      GPG_USER_MAP_PASSPHRASE:
        required: true

jobs:
  slack_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Call Slack Notification Workflow (Decrypt JSON)
        id: decrypt_slack_map
        uses: ./github/workflows/user_map_decrypt.yml
        env:
          GPG_USER_MAP_PASSPHRASE: ${{ secrets.GPG_USER_MAP_PASSPHRASE }}
      
      - name: Load the decrypted Slack Users Map
        id: load_users
        run: |
          # Load the Slack Users Map from the previous workflow
          SLACK_USERS_MAP="${{ env.slack_users_map }}"
          echo "SLACK_USERS_MAP: $SLACK_USERS_MAP"
          GITHUB_USER="${{ github.actor }}"
          
          # Use jq to extract the Slack user ID from the JSON
          SLACK_USER_ID=$(echo "$SLACK_USERS_MAP" | jq -r --arg user "$GITHUB_USER" '.[$user]')
          
          # Check if the Slack user ID was found
          if [ "$SLACK_USER_ID" == "null" ] || [ -z "$SLACK_USER_ID" ]; then
              echo "Slack user ID not found for GitHub user: $GITHUB_USER. Fallback to general channel."
              SLACK_USER_ID="${{ secrets.GENERAL_CHANNEL_ID }}"
              SLACK_MESSAGE=":warning: *GitHub user $GITHUB_USER is not mapped in Slack users.* Fallback to general channel.\n*PR Notification* :x:"
          else
              SLACK_MESSAGE="*PR Notification* :x:"
          fi
          
          # Set Slack user ID and message as environment variables
          echo "SLACK_USER_ID=$SLACK_USER_ID" >> $GITHUB_ENV
          echo "SLACK_MESSAGE=$SLACK_MESSAGE" >> $GITHUB_ENV

      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: ${{ env.SLACK_USER_ID }}
          slack-message: |
            ${{ env.SLACK_MESSAGE }}
            *Repository*: ${{ github.repository }}
            *Pull Request*: ${{ github.event.pull_request.title }}
            *Action*: ${{ github.event.action }}
            *PR URL*: ${{ github.event.pull_request.html_url }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
